spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security6
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false